In [ ]:
import sqlite3
from project_starter import init_database
from sqlalchemy import create_engine

# Database initialization is a separate setup step, never part of Run All.
# Uncomment init_database to reset the database to its starting state.
conn = sqlite3.connect("munder_difflin.db")
db_engine = create_engine("sqlite:///munder_difflin.db")
# init_database(db_engine)

In [7]:
import pandas as pd

# Query the sqlite_master system table
query = "SELECT name FROM sqlite_master WHERE type='table';"
df_tables = pd.read_sql_query(query, conn)
df_tables

             name
0    transactions
1  quote_requests
2          quotes
3       inventory
4  paper_supplies

In [8]:
pd.read_sql("select * from transactions", conn)

,id,item_name,transaction_type,units,price,transaction_date
0,None,NaN,sales,NaN,50000.00,2025-01-01T00:00:00
1,None,Paper plates,stock_orders,748.0,74.80,2025-01-01T00:00:00
2,None,100 lb cover stock,stock_orders,636.0,318.00,2025-01-01T00:00:00
3,None,Glossy paper,stock_orders,587.0,117.40,2025-01-01T00:00:00
4,None,Rolls of banner paper (36-inch width),stock_orders,546.0,1365.00,2025-01-01T00:00:00
5,None,Photo paper,stock_orders,423.0,105.75,2025-01-01T00:00:00
6,None,Cardstock,stock_orders,595.0,89.25,2025-01-01T00:00:00
7,None,Colored paper,stock_orders,788.0,78.80,2025-01-01T00:00:00
8,None,80 lb text paper,stock_orders,249.0,99.60,2025-01-01T00:00:00
9,None,Large poster paper (24x36 inches),stock_orders,699.0,699.00,2025-01-01T00:00:00
10,None,Table covers,stock_orders,736.0,1104.00,2025-01-01T00:00:00
11,None,Butcher paper,stock_orders,365.0,36.50,2025-01-01T00:00:00
12,None,Kraft paper,stock_orders,493.0,49.30,2025-01-01T00:00:00
13,None,Banner paper,stock_orders,793.0,237.90,2025-01-01T00:00:00
14,None,Presentation folders,stock_orders,389.0,194.50,2025-01-01T00:00:00
15,None,Patterned paper,stock_orders,548.0,82.20,2025-01-01T00:00:00
16,None,A4 paper,stock_orders,272.0,13.60,2025-01-01T00:00:00
17,None,Invitation cards,stock_orders,526.0,263.00,2025-01-01T00:00:00
18,None,Crepe paper,stock_orders,234.0,11.70,2025-01-01T00:00:00
19,None,250 gsm cardstock,stock_orders,436.0,130.80,2025-01-01T00:00:00
20,None,Legal-size paper,stock_orders,481.0,38.48,2025-01-01T00:00:00
21,None,Notepads,stock_orders,399.0,798.00,2025-01-01T00:00:00
22,None,220 gsm poster paper,stock_orders,356.0,124.60,2025-01-01T00:00:00
23,None,Paper cups,stock_orders,651.0,52.08,2025-01-01T00:00:00
24,None,Paper napkins,stock_orders,418.0,8.36,2025-01-01T00:00:00
25,None,Matte paper,stock_orders,448.0,80.64,2025-01-01T00:00:00
26,None,Letterhead paper,stock_orders,627.0,75.24,2025-01-01T00:00:00
27,None,Recycled paper,stock_orders,355.0,28.40,2025-01-01T00:00:00
28,None,Flyers,stock_orders,492.0,73.80,2025-01-01T00:00:00
29,None,Eco-friendly paper,stock_orders,605.0,72.60,2025-01-01T00:00:00
30,None,Decorative adhesive tape (washi tape),stock_orders,256.0,51.20,2025-01-01T00:00:00
31,None,Wrapping paper,stock_orders,367.0,55.05,2025-01-01T00:00:00
32,None,Heavyweight paper,stock_orders,799.0,159.80,2025-01-01T00:00:00
33,None,Sticky notes,stock_orders,613.0,18.39,2025-01-01T00:00:00
34,None,Party streamers,stock_orders,707.0,35.35,2025-01-01T00:00:00
35,None,Paper party bags,stock_orders,764.0,191.00,2025-01-01T00:00:00
36,None,Disposable cups,stock_orders,535.0,53.50,2025-01-01T00:00:00
37,None,Poster paper,stock_orders,418.0,104.50,2025-01-01T00:00:00
38,None,Bright-colored paper,stock_orders,286.0,34.32,2025-01-01T00:00:00
39,None,Standard copy paper,stock_orders,696.0,27.84,2025-01-01T00:00:00
40,None,Letter-sized paper,stock_orders,699.0,41.94,2025-01-01T00:00:00
41,None,Decorative paper,stock_orders,335.0,60.30,2025-01-01T00:00:00
42,None,Construction paper,stock_orders,796.0,55.72,2025-01-01T00:00:00
43,None,Uncoated paper,stock_orders,307.0,18.42,2025-01-01T00:00:00
44,None,Glitter paper,stock_orders,725.0,159.50,2025-01-01T00:00:00
45,None,Name tags with lanyards,stock_orders,217.0,162.75,2025-01-01T00:00:00
46,None,Envelopes,stock_orders,458.0,22.90,2025-01-01T00:00:00

In [ ]:
pd.read_sql("select * from quote_requests", conn)

In [ ]:
pd.read_sql("select * from quotes", conn)

In [ ]:
pd.read_sql("select * from inventory", conn)

### Configuration

In [1]:
from model_config import create_model

model = create_model()

/Users/jameschang/Downloads/agentic-ai-c4-exercises-demos/project/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

#### RequestUnderstandingAgent

In [2]:
from request_schema import ParsedItems
from request_schema import paper_supplies
from request_understanding_agent import RequestUnderstandingAgent

request_understanding_agent = RequestUnderstandingAgent(model=model)
result = request_understanding_agent.run(
    """I would like to request the following paper supplies for the ceremony: 

- 200 sheets of A4 glossy paper
- 100 sheets of heavy cardstock (white)
- 100 sheets of colored paper (assorted colors)

I need these supplies delivered by April 15, 2025. Thank you."""
)

parsed = (
    ParsedItems.model_validate_json(result)
    if isinstance(result, str)
    else ParsedItems.model_validate(result)
)

if any(item.current_stock is not None for item in parsed.items):
    raise ValueError(
        "The parsing agent must return current_stock as null; "
        "inventory tools populate it later."
    )

print(parsed.model_dump_json(indent=2))

╭───────────────────────────────────── New run - request_understanding_agent ─────────────────────────────────────╮
│                                                                                                                 │
│ I would like to request the following paper supplies for the ceremony:                                          │
│                                                                                                                 │
│ - 200 sheets of A4 glossy paper                                                                                 │
│ - 100 sheets of heavy cardstock (white)                                                                         │
│ - 100 sheets of colored paper (assorted colors)                                                                 │
│                                                                                                                 │
│ I need these supplies delivered by April 15, 2025. Thank you.                                                   │
│                                                                                                                 │
╰─ OpenAIModel - gpt-5.6-luna ────────────────────────────────────────────────────────────────────────────────────╯

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Calling tool: 'final_answer' with arguments: {'answer':                                                         │
│ '{"message_scope":"in_scope","mood":null,"items":[{"customer_description":"200 sheets of A4 glossy              │
│ paper","match_status":"matched","item_name":"Glossy                                                             │
│ paper","category":"paper","unit_price":0.2,"min_stock_level":147,"units":200,"quantity_unit":"sheet","package_s │
│ ize":null,"package_unit":null,"current_stock":null,"clarification_question":null},{"customer_description":"100  │
│ sheets of heavy cardstock                                                                                       │
│ (white)","match_status":"matched","item_name":"Cardstock","category":"paper","unit_price":0.15,"min_stock_level │
│ ":148,"units":100,"quantity_unit":"sheet","package_size":null,"package_unit":null,"current_stock":null,"clarifi │
│ cation_question":null},{"customer_description":"100 sheets of colored paper (assorted                           │
│ colors)","match_status":"matched","item_name":"Colored                                                          │
│ paper","category":"paper","unit_price":0.1,"min_stock_level":143,"units":100,"quantity_unit":"sheet","package_s │
│ ize":null,"package_unit":null,"current_stock":null,"clarification_question":null}],"delivery_by":"2025-04-15"," │
│ delivery_date_question":null}'}                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Observations: {"message_scope":"in_scope","mood":null,"items":|{"customer_description":"200 sheets of A4 glossy
paper","match_status":"matched","item_name":"Glossy
paper","category":"paper","unit_price":0.2,"min_stock_level":147,"units":200,"quantity_unit":"sheet","package_size"
:null,"package_unit":null,"current_stock":null,"clarification_question":null},{"customer_description":"100 sheets
of heavy cardstock
(white)","match_status":"matched","item_name":"Cardstock","category":"paper","unit_price":0.15,"min_stock_level":14
8,"units":100,"quantity_unit":"sheet","package_size":null,"package_unit":null,"current_stock":null,"clarification_q
uestion":null},{"customer_description":"100 sheets of colored paper (assorted
colors)","match_status":"matched","item_name":"Colored
paper","category":"paper","unit_price":0.1,"min_stock_level":143,"units":100,"quantity_unit":"sheet","package_size"
:null,"package_unit":null,"current_stock":null,"clarification_question":null}],"delivery_by":"2025-04-15","delivery
_date_question":null}

Final answer: {"message_scope":"in_scope","mood":null,"items":[{"customer_description":"200 sheets of A4 glossy
paper","match_status":"matched","item_name":"Glossy
paper","category":"paper","unit_price":0.2,"min_stock_level":147,"units":200,"quantity_unit":"sheet","package_size"
:null,"package_unit":null,"current_stock":null,"clarification_question":null},{"customer_description":"100 sheets
of heavy cardstock
(white)","match_status":"matched","item_name":"Cardstock","category":"paper","unit_price":0.15,"min_stock_level":14
8,"units":100,"quantity_unit":"sheet","package_size":null,"package_unit":null,"current_stock":null,"clarification_q
uestion":null},{"customer_description":"100 sheets of colored paper (assorted
colors)","match_status":"matched","item_name":"Colored
paper","category":"paper","unit_price":0.1,"min_stock_level":143,"units":100,"quantity_unit":"sheet","package_size"
:null,"package_unit":null,"current_stock":null,"clarification_question":null}],"delivery_by":"2025-04-15","delivery
_date_question":null}

[Step 1: Duration 4.29 seconds| Input tokens: 6,472 | Output tokens: 265]

{
  "message_scope": "in_scope",
  "mood": null,
  "items": [
    {
      "customer_description": "200 sheets of A4 glossy paper",
      "match_status": "matched",
      "item_name": "Glossy paper",
      "category": "paper",
      "unit_price": 0.2,
      "min_stock_level": 147,
      "units": 200,
      "quantity_unit": "sheet",
      "package_size": null,
      "package_unit": null,
      "current_stock": null,
      "clarification_question": null
    },
    {
      "customer_description": "100 sheets of heavy cardstock (white)",
      "match_status": "matched",
      "item_name": "Cardstock",
      "category": "paper",
      "unit_price": 0.15,
      "min_stock_level": 148,
      "units": 100,
      "quantity_unit": "sheet",
      "package_size": null,
      "package_unit": null,
      "current_stock": null,
      "clarification_question": null
    },
    {
      "customer_description": "100 sheets of colored paper (assorted colors)",
      "match_status": "matched",
      "item_name": "Colored paper",
      "category": "paper",
      "unit_price": 0.1,
      "min_stock_level": 143,
      "units": 100,
      "quantity_unit": "sheet",
      "package_size": null,
      "package_unit": null,
      "current_stock": null,
      "clarification_question": null
    }
  ],
  "delivery_by": "2025-04-15",
  "delivery_date_question": null
}

#### InventoryManagementAgent

In [3]:
from inventory_management_agent import InventoryManagementAgent

inventory_management_agent = InventoryManagementAgent(model=model)
request_date = "04/03/25"
task = (
    "Plan stock and replenishment for this request.\n"
    f"Request date (MM/DD/YY): {request_date}\n"
    "Structured request:\n" + parsed.model_dump_json()
)
result = inventory_management_agent.run(task)

╭───────────────────────────────────── New run - inventory_management_agent ──────────────────────────────────────╮
│                                                                                                                 │
│ Plan stock and replenishment for this request.                                                                  │
│ Request date (MM/DD/YY): 04/03/25                                                                               │
│ Structured request:                                                                                             │
│ {"message_scope":"in_scope","mood":null,"items":[{"customer_description":"200 sheets of A4 glossy               │
│ paper","match_status":"matched","item_name":"Glossy                                                             │
│ paper","category":"paper","unit_price":0.2,"min_stock_level":147,"units":200,"quantity_unit":"sheet","package_s │
│ ize":null,"package_unit":null,"current_stock":null,"clarification_question":null},{"customer_description":"100  │
│ sheets of heavy cardstock                                                                                       │
│ (white)","match_status":"matched","item_name":"Cardstock","category":"paper","unit_price":0.15,"min_stock_level │
│ ":148,"units":100,"quantity_unit":"sheet","package_size":null,"package_unit":null,"current_stock":null,"clarifi │
│ cation_question":null},{"customer_description":"100 sheets of colored paper (assorted                           │
│ colors)","match_status":"matched","item_name":"Colored                                                          │
│ paper","category":"paper","unit_price":0.1,"min_stock_level":143,"units":100,"quantity_unit":"sheet","package_s │
│ ize":null,"package_unit":null,"current_stock":null,"clarification_question":null}],"delivery_by":"2025-04-15"," │
│ delivery_date_question":null}                                                                                   │
│                                                                                                                 │
╰─ OpenAIModel - gpt-5.6-luna ────────────────────────────────────────────────────────────────────────────────────╯

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Calling tool: 'plan_replenishment' with arguments: {'parsed': {'message_scope': 'in_scope', 'mood': None,       │
│ 'items': [{'customer_description': '200 sheets of A4 glossy paper', 'match_status': 'matched', 'item_name':     │
│ 'Glossy paper', 'category': 'paper', 'unit_price': 0.2, 'min_stock_level': 147, 'units': 200, 'quantity_unit':  │
│ 'sheet', 'package_size': None, 'package_unit': None, 'current_stock': None, 'clarification_question': None},    │
│ {'customer_description': '100 sheets of heavy cardstock (white)', 'match_status': 'matched', 'item_name':       │
│ 'Cardstock', 'category': 'paper', 'unit_price': 0.15, 'min_stock_level': 148, 'units': 100, 'quantity_unit':    │
│ 'sheet', 'package_size': None, 'package_unit': None, 'current_stock': None, 'clarification_question': None},    │
│ {'customer_description': '100 sheets of colored paper (assorted colors)', 'match_status': 'matched',            │
│ 'item_name': 'Colored paper', 'category': 'paper', 'unit_price': 0.1, 'min_stock_level': 143, 'units': 100,     │
│ 'quantity_unit': 'sheet', 'package_size': None, 'package_unit': None, 'current_stock': None,                    │
│ 'clarification_question': None}], 'delivery_by': '2025-04-15', 'delivery_date_question': None}, 'as_of_date':   │
│ '04/03/25'}                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Observations: |{'item_name': 'Glossy paper', 'unit_price': 0.2, 'requested_units': 200, 'current_stock': 587,
'ordered_units': 0, 'ship_date': '2025-04-03', 'on_time': True, 'can_fulfill': True, 'reject_reason': None},
{'item_name': 'Cardstock', 'unit_price': 0.15, 'requested_units': 100, 'current_stock': 595, 'ordered_units': 0,
'ship_date': '2025-04-03', 'on_time': True, 'can_fulfill': True, 'reject_reason': None}, {'item_name': 'Colored
paper', 'unit_price': 0.1, 'requested_units': 100, 'current_stock': 788, 'ordered_units': 0, 'ship_date':
'2025-04-03', 'on_time': True, 'can_fulfill': True, 'reject_reason': None}]

[Step 1: Duration 3.56 seconds| Input tokens: 1,543 | Output tokens: 270]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Calling tool: 'final_answer' with arguments: {'answer': '[{"item_name":"Glossy                                  │
│ paper","unit_price":0.2,"requested_units":200,"current_stock":587,"ordered_units":0,"ship_date":"2025-04-03","o │
│ n_time":true,"can_fulfill":true,"reject_reason":null},{"item_name":"Cardstock","unit_price":0.15,"requested_uni │
│ ts":100,"current_stock":595,"ordered_units":0,"ship_date":"2025-04-03","on_time":true,"can_fulfill":true,"rejec │
│ t_reason":null},{"item_name":"Colored                                                                           │
│ paper","unit_price":0.1,"requested_units":100,"current_stock":788,"ordered_units":0,"ship_date":"2025-04-03","o │
│ n_time":true,"can_fulfill":true,"reject_reason":null}]'}                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Observations: |{"item_name":"Glossy
paper","unit_price":0.2,"requested_units":200,"current_stock":587,"ordered_units":0,"ship_date":"2025-04-03","on_ti
me":true,"can_fulfill":true,"reject_reason":null},{"item_name":"Cardstock","unit_price":0.15,"requested_units":100,
"current_stock":595,"ordered_units":0,"ship_date":"2025-04-03","on_time":true,"can_fulfill":true,"reject_reason":nu
ll},{"item_name":"Colored
paper","unit_price":0.1,"requested_units":100,"current_stock":788,"ordered_units":0,"ship_date":"2025-04-03","on_ti
me":true,"can_fulfill":true,"reject_reason":null}]

Final answer: [{"item_name":"Glossy
paper","unit_price":0.2,"requested_units":200,"current_stock":587,"ordered_units":0,"ship_date":"2025-04-03","on_ti
me":true,"can_fulfill":true,"reject_reason":null},{"item_name":"Cardstock","unit_price":0.15,"requested_units":100,
"current_stock":595,"ordered_units":0,"ship_date":"2025-04-03","on_time":true,"can_fulfill":true,"reject_reason":nu
ll},{"item_name":"Colored
paper","unit_price":0.1,"requested_units":100,"current_stock":788,"ordered_units":0,"ship_date":"2025-04-03","on_ti
me":true,"can_fulfill":true,"reject_reason":null}]

[Step 2: Duration 2.54 seconds| Input tokens: 3,681 | Output tokens: 456]

#### QuotingAgent

In [5]:
from pricing import price_quote

quote = price_quote(parsed)
quote

Quote(lines=[QuoteLine(item_name='Glossy paper', quantity=200, unit='sheet', unit_price=0.25, list_total=50.0, sale_price=50.0), QuoteLine(item_name='Cardstock', quantity=100, unit='sheet', unit_price=0.1875, list_total=18.75, sale_price=18.75), QuoteLine(item_name='Colored paper', quantity=100, unit='sheet', unit_price=0.125, list_total=12.5, sale_price=12.5)], unpriced=[], subtotal=81.25, discount_rate=0.0, discount_amount=0.0, total=81.25, rationale='Prices are our standard list prices per sheet, piece or roll. Orders of $500 or more receive a 5% bulk discount. Total: $81.25.', cost=65.0, gross_margin=0.2)

#### Orchestrator

In [ ]:
from orchestrator import Orchestrator

# Stop at the quote so these demos don't record sales in the database.
orchestrator = Orchestrator(model=model, auto_confirm=False)
request_date = "2025-04-03"

In [ ]:
# 1. Normal case
orchestrator.start_conversation()
result = orchestrator.process_customer_message(
    "I would like to place an order for 500 sheets of high-quality glossy paper and 300 sheets of sturdy cardstock for our upcoming show. We need the supplies delivered by April 15, 2025.",
    request_date,
    request_id=1,
)

print("Status:", result["status"])
print("Assistant:", result["reply"])

In [ ]:
# 2. Missing information, then the customer's answer in the same conversation
orchestrator.start_conversation()
result = orchestrator.process_customer_message(
    "I would like to order A4 paper.", request_date, request_id=2
)
print("Status:", result["status"])
print("Assistant:", result["reply"])

result = orchestrator.process_customer_message(
    "2 reams, delivered by April 15, 2025.", request_date, request_id=2
)
print("Status:", result["status"])
print("Assistant:", result["reply"])

In [ ]:
# 3. Out-of-scope question
orchestrator.start_conversation()
result = orchestrator.process_customer_message(
    "I would like to book a flight to Paris.", request_date, request_id=3
)

print("Status:", result["status"])
print("Assistant:", result["reply"])